# This is a basic workflow to help you get started with Actions

name: CI Docker Stata

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build and push base-stata
        env:
          # environment variables
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          cd ./base-stata
          wget -q -O stata.tar.gz ${URL}
          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
          docker build -t base-stata .
          docker tag base-stata:latest ledwindra/base-stata:latest
          docker push ledwindra/base-stata:latest


      - name: Build and push jupyter-stata
        uses: actions/checkout@v2
        env:
          # environment variables
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          cd ./jupyter-stata
          wget -q -O stata.tar.gz ${URL}
          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
          docker build -t jupyter-stata .
          docker tag jupyter-stata:latest ledwindra/jupyter-stata:latest
          docker push ledwindra/jupyter-stata:latest